# Default values for load-gen
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# These default values will generate ~ 1000 milli-cpus of load
threads: "10"
primes: "2000000"

image:
  repository: ruby
  tag: 2.3.3-alpine
  pullPolicy: Always
resources:
  limits:
    cpu: 2000m
    memory: 2048Mi
  requests:
    cpu: 2000m
    memory: 1024Mi
